### ISSUE TITLE
Option to drop down menu to the left?

### ISSUE THREAD

**Issue by mritzman-dg** [jonataswalker/ol3-contextmenu#64] opened 2016-09-22 16:12 UTC
Is there an option to be able to show the menu to the left of the mouse instead of the right?

**Comment by jonataswalker** [comment] 2016-09-23 10:16
Duplicate of #54.

I'll add an option as soon as possible.

**Closed by jonataswalker** 2016-09-23 10:16 UTC

**Comment by mritzman-dg** [comment] 2016-09-23 16:33
Thanks! By the way I made the following changes farther below to [ol3-contextmenu-debug.js](https://raw.githubusercontent.com/jonataswalker/ol3-contextmenu/master/build/ol3-contextmenu-debug.js) which works for my purposes since I don't have any sub menus.  I'm sure you'll want clean it up and add code to handle sub menus...

Change on line 277:
![image](https://cloud.githubusercontent.com/assets/20933623/18793585/a0eae1ce-8178-11e6-93ae-cac79d6e0523.png)

```
var defaultOptions = {
  width: 150,
  default_items: true,
  position: "right"
};
```

Changes within positionContainer function:
![image](https://cloud.githubusercontent.com/assets/20933623/18793593/ad717192-8178-11e6-9f2c-0f71b6f44e73.png)

```
if(this.Base.options.position == "left") {
  var space_right_w = pixel[0];
  if(space_right_w >= menu_size.w) {
    this.Base.container.style.left = (pixel[0] - menu_size.w) + "px";
    this.Base.container.style.right = 'auto';
  } else {
    this.Base.container.style.right = 'auto';
    this.Base.container.style.left = '15px';
  }
} else {
  if (space_left_w >= menu_size.w) {
    this.Base.container.style.right = 'auto';
    this.Base.container.style.left = (pixel[0] + 5) + "px";
  } else {
    this.Base.container.style.left = 'auto';
    this.Base.container.style.right = '15px';
  }
}
```

**Comment by jonataswalker** [comment] 2016-09-23 17:03
Hmm and how does it look like?

**Comment by mritzman-dg** [comment] 2016-09-27 15:52
Looks good, menu is positioned to the left.  Just doesn't handle sub menus.

**Comment by jonataswalker** [comment] 2016-09-27 16:50
May you upload a screenshot?

**Comment by mritzman-dg** [comment] 2016-09-28 15:42
Here is a screenshot.  We have a tooltip on the right side so I put the drop down on the left.  There are no sub menus so there will be some extra code needed to handle those items.

![rightclickmenudropdownleft](https://cloud.githubusercontent.com/assets/20933623/18920813/c3b26976-855f-11e6-9ec0-130a724ab7bb.png)
